### ISSUE TITLE
It does not look like the pvals for stationary or non-stationary are correct

### ISSUE THREAD

**Issue by maallen3** [azofeifa/gTFIv2#1]
you have 
  vector<double> MD_scores              = {MD_score, MD_score_TSS, MD_score_NON};
  vector<vector<vector<double>>> CDFS   = {MD_CDF, MD_CDF_NON, MD_CDF_TSS};

  for (int l = 0 ; l < 3; l++){
    vector<vector<double>> CDF  = CDFS[l];
    double score                                = MD_scores[l];
    int i       = 0;
    int J=0;

    while (i < CDF.size()-1){
      if (CDF[i][0] >= score ){
        J++;
      }
      i++;
    }
    double pv                   = float(J) / CDF.size();
    double mean_ns              = get_mean(CDF);
    double std_ns               = sqrt(get_var(CDF, mean_ns)) ;

    double mean                 = total*prob;
    double std                  = sqrt(mean*(1-prob));
    double z_score              = (score*total - mean)/std;
    double z_score2             = (score - mean_ns)/std_ns;
    double pv_s                 = 1.0 - 0.5*(1+erf(z_score));
    double pv_ns                = 1.0 - 0.5*(1+erf(z_score2));

    non_pvalues.push_back(log10(pv_s+pow(10,-40)));
    stationary_p_values.push_back(log10(pv_ns+pow(10,-40)));
    
I think it should be (YOUR code commented out)
  vector<double> MD_scores              = {MD_score_NON, MD_score_TSS, MD_score};//{MD_score, MD_score_TSS, MD_score_NON};
  vector<vector<vector<double>>> CDFS   = {MD_CDF_NON, MD_CDF_TSS,MD_CDF};//{MD_CDF, MD_CDF_NON, MD_CDF_TSS};

  for (int l = 0 ; l < 3; l++){
    vector<vector<double>> CDF  = CDFS[l];
    double score                                = MD_scores[l];
    int i       = 0;
    int J=0;

    while (i < CDF.size()-1){
      if (CDF[i][0] >= score ){
        J++;
      }
      i++;
    }
    double pv                   = float(J) / CDF.size();
    double mean_ns              = get_mean(CDF);
    double std_ns               = sqrt(get_var(CDF, mean_ns)) ;

    double mean                 = total*prob;
    double std                  = sqrt(mean*(1-prob));
    double z_score              = (score*total - mean)/std;
    double z_score2             = (score - mean_ns)/std_ns;
    double pv_s                 = 1.0 - 0.5*(1+erf(z_score));
    double pv_ns                = 1.0 - 0.5*(1+erf(z_score2));

    //non_pvalues.push_back(log10(pv_s+pow(10,-40)));
    //stationary_p_values.push_back(log10(pv_ns+pow(10,-40)));
    non_pvalues.push_back(log10(pv_ns+pow(10,-40)));
    stationary_p_values.push_back(log10(pv_s+pow(10,-40)));

**Comment by azofeifa** [comment]
all notions of p-values are being removed with this MDS C application, they will be put into the python motif_displacement_package, stay tuned!
